Repository so2zy/so2zy_BE, pull requests merged in 2023-11, with the labels that each got.

#12 feat: global exception handling 추가
  build.gradle
  src/main/java/com/aroom/global/error/ErrorCode.java
  src/main/java/com/aroom/global/error/GlobalExceptionHandler.java
  src/main/java/com/aroom/global/error/ServiceException.java
  src/main/java/com/aroom/global/response/ApiResponse.java
Labels: enhancement

#14 Feat/#13 create domain entity
  src/main/java/com/aroom/domain/accommodation/model/Accommodation.java
  src/main/java/com/aroom/domain/accommodation/model/AccommodationImage.java
  src/main/java/com/aroom/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/aroom/domain/cart/model/Cart.java
  src/main/java/com/aroom/domain/cart/repository/CartRepository.java
  src/main/java/com/aroom/domain/favorite/model/Favorite.java
  src/main/java/com/aroom/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/aroom/domain/member/model/Member.java
  src/main/java/com/aroom/domain/member/repository/MemberRepository.java
  src/main/java/com/aroom/domain/order/model/Order.java
  src/main/java/com/aroom/domain/order/repository/OrderRepository.java
  src/main/java/com/aroom/domain/order_room/model/OrderRoom.java
  src/main/java/com/aroom/domain/order_room/repository/OrderRoomRepository.java
  src/main/java/com/aroom/domain/room/model/Room.java
  src/main/java/com/aroom/domain/room/model/RoomImage.java
  src/main/java/com/aroom/domain/room/repository/RoomRepository.java
  src/main/java/com/aroom/domain/room_cart/model/RoomCart.java
  src/main/java/com/aroom/domain/room_cart/repository/RoomCartRepository.java
Labels: enhancement

#16 Feat/#15 fix order entity name
  .env
  src/main/java/com/aroom/domain/accommodation/repository/AccommodationImageRepository.java
  src/main/java/com/aroom/domain/order/model/Reservation.java
  src/main/java/com/aroom/domain/order/repository/OrderRepository.java
  src/main/java/com/aroom/domain/order/repository/ReservationRepository.java
  src/main/java/com/aroom/domain/order_room/model/ReservationRoom.java
  src/main/java/com/aroom/domain/order_room/repository/OrderRoomRepository.java
  src/main/java/com/aroom/domain/order_room/repository/ReservationRoomRepository.java
  src/main/java/com/aroom/domain/room/repository/RoomImageRepository.java
Labels: enhancement

#20 ƒeat: JWT 발급 유틸 클래스 추가
  build.gradle
  src/main/java/com/aroom/global/jwt/JwtPayload.java
  src/main/java/com/aroom/global/jwt/JwtUtils.java
  src/main/resources/application-local.yaml
  src/test/java/com/aroom/global/jwt/JwtUtilsTest.java
  src/test/resources/application.yaml
Labels: enhancement

#21 Feat/#4 reservation controller
  src/main/java/com/aroom/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/aroom/domain/reservation/dto/request/ReservationRequest.java
  src/main/java/com/aroom/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/aroom/domain/reservation/model/Reservation.java
  src/main/java/com/aroom/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
  src/main/java/com/aroom/domain/reservationRoom/model/ReservationRoom.java
  src/main/java/com/aroom/domain/reservationRoom/repository/ReservationRoomRepository.java
  src/main/java/com/aroom/domain/room/dto/request/ReservationRoomRequest.java
  src/main/java/com/aroom/domain/roomCart/model/RoomCart.java
  src/main/java/com/aroom/domain/roomCart/repository/RoomCartRepository.java
  src/test/java/com/aroom/domain/reservation/controller/ReservationRestControllerTest.java
Labels: enhancement

#26 Feat/`AccessToken 재발급` 기능 추가
  build.gradle
  src/main/java/com/aroom/global/config/RedisConfig.java
  src/main/java/com/aroom/global/jwt/controller/JwtRefreshRestController.java
  src/main/java/com/aroom/global/jwt/controller/RefreshAccessTokenRequest.java
  src/main/java/com/aroom/global/jwt/exception/BadTokenException.java
  src/main/java/com/aroom/global/jwt/exception/TokenExpiredException.java
  src/main/java/com/aroom/global/jwt/model/JwtEntity.java
  src/main/java/com/aroom/global/jwt/model/TokenType.java
  src/main/java/com/aroom/global/jwt/repository/JwtCacheRepository.java
  src/main/java/com/aroom/global/jwt/repository/JwtRedisRepository.java
  src/main/java/com/aroom/global/jwt/repository/JwtRepository.java
  src/main/java/com/aroom/global/jwt/service/JwtService.java
  src/main/java/com/aroom/global/jwt/service/TokenResponse.java
  src/test/java/com/aroom/global/jwt/controller/JwtRefreshRestControllerTest.java
  src/test/java/com/aroom/global/jwt/service/JwtServiceTest.java
Labels: enhancement

#28 test: 예약 기능 repository 테스트 코드 작성
  src/test/java/com/aroom/domain/reservation/repository/ReservationRepositoryTest.java
Labels: enhancement

#32 chore: CI.yml 작성
  .github/workflows/CI.yml
Labels: documentation

#24 feat/#5 room get
  .env.sample
  src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestController.java
  src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerAdvice.java
  src/main/java/com/aroom/domain/accommodation/dto/response/AccommodationResponseDTO.java
  src/main/java/com/aroom/domain/accommodation/dto/response/RoomListInfoDTO.java
  src/main/java/com/aroom/domain/accommodation/exception/AccommodationNotFoundException.java
  src/main/java/com/aroom/domain/accommodation/model/Accommodation.java
  src/main/java/com/aroom/domain/accommodation/model/AccommodationImage.java
  src/main/java/com/aroom/domain/accommodation/service/AccommodationService.java
  src/main/java/com/aroom/domain/room/model/Room.java
  src/main/java/com/aroom/domain/room/model/RoomImage.java
  src/test/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerTest.java
  src/test/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/aroom/domain/accommodation/service/AccommodationServiceTest.java
Labels: enhancement

#27 Feat/#4 reservation service
  http/save_reservation.http
  src/main/java/com/aroom/domain/cart/model/Cart.java
  src/main/java/com/aroom/domain/member/model/Member.java
  src/main/java/com/aroom/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/aroom/domain/reservation/dto/request/ReservationRequest.java
  src/main/java/com/aroom/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/aroom/domain/reservation/exception/MaximumCapacityExceededException.java
  src/main/java/com/aroom/domain/reservation/exception/OutOfStockException.java
  src/main/java/com/aroom/domain/reservation/exception/ReservationErrorCode.java
  src/main/java/com/aroom/domain/reservation/exception/ReservationExceptionHandler.java
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
  src/main/java/com/aroom/domain/reservationRoom/model/ReservationRoom.java
  src/main/java/com/aroom/domain/reservationRoom/repository/ReservationRoomRepository.java
  src/main/java/com/aroom/domain/room/dto/request/RoomReservationRequest.java
  src/main/java/com/aroom/domain/room/dto/response/RoomImageResponse.java
  src/main/java/com/aroom/domain/room/dto/response/RoomReservationResponse.java
  src/main/java/com/aroom/domain/room/repository/RoomRepository.java
  src/main/java/com/aroom/domain/roomCart/repository/RoomCartRepository.java
  src/test/java/com/aroom/domain/reservation/controller/ReservationRestControllerTest.java
  src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
Labels: enhancement

#40 Feat/#3 login with security
  build.gradle
  src/main/java/com/aroom/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/aroom/global/config/CustomHttpHeaders.java
  src/main/java/com/aroom/global/resolver/Login.java
  src/main/java/com/aroom/global/resolver/LoginInfo.java
  src/main/java/com/aroom/global/resolver/LoginInfoArgumentResolver.java
  src/main/java/com/aroom/global/security/SecurityConfig.java
  src/main/java/com/aroom/global/security/SecurityFilterConfig.java
  src/main/java/com/aroom/global/security/account/AccountContext.java
  src/main/java/com/aroom/global/security/account/CustomUserDetailsService.java
  src/main/java/com/aroom/global/security/formlogin/CustomFormLoginFilter.java
  src/main/java/com/aroom/global/security/formlogin/CustomFormLoginProvider.java
  src/main/java/com/aroom/global/security/formlogin/CustomLoginToken.java
  src/main/java/com/aroom/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/aroom/global/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/aroom/global/security/jwt/JwtAuthenticationToken.java
Labels: enhancement

#35 Feat/#33 set auditing entity
  src/main/java/com/aroom/AroomBeApplication.java
  src/main/java/com/aroom/domain/accommodation/model/Accommodation.java
  src/main/java/com/aroom/domain/accommodation/model/AccommodationImage.java
  src/main/java/com/aroom/domain/cart/model/Cart.java
  src/main/java/com/aroom/domain/favorite/model/Favorite.java
  src/main/java/com/aroom/domain/member/model/Member.java
  src/main/java/com/aroom/domain/reservation/model/Reservation.java
  src/main/java/com/aroom/domain/reservationRoom/model/ReservationRoom.java
  src/main/java/com/aroom/domain/room/model/Room.java
  src/main/java/com/aroom/domain/room/model/RoomImage.java
  src/main/java/com/aroom/domain/roomCart/model/RoomCart.java
  src/main/java/com/aroom/global/basetime/BaseTimeEntity.java
  src/main/java/com/aroom/global/config/JpaConfig.java
  src/test/java/com/aroom/global/basetime/BaseTimeEntityTest.java
Labels: enhancement

#50 Feature/#44 fix reservation test code
  src/main/java/com/aroom/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/aroom/domain/reservation/model/Reservation.java
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
  src/test/java/com/aroom/domain/reservation/controller/ReservationRestControllerTest.java
  src/test/java/com/aroom/domain/reservation/repository/ReservationRepositoryTest.java
  src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
Labels: enhancement

#59 hotfix: spring security 수정
  src/main/java/com/aroom/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/aroom/global/security/SecurityConfig.java
  src/main/java/com/aroom/global/security/SecurityFilterConfig.java
Labels: bug

#62 fix: CORS Setting
  build.gradle
  src/main/java/com/aroom/global/security/SecurityConfig.java
  src/main/java/com/aroom/global/security/SecurityFilterConfig.java
Labels: bug

#63 refactor : Querydsl 로직 버그 수정 및 페이지네이션 버그 수정
  src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestController.java
  src/main/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryImpl.java
Labels: bug

#66 fix: Member Index 제거
  src/main/java/com/aroom/domain/member/model/Member.java
  src/test/java/com/aroom/domain/member/service/MemberServiceTest.java
Labels: bug

#68 refactor: email 제거, name 추가
  src/main/java/com/aroom/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
  src/main/java/com/aroom/global/jwt/JwtUtils.java
  src/main/java/com/aroom/global/jwt/dto/JwtCreateRequest.java
  src/main/java/com/aroom/global/jwt/model/JwtPayload.java
  src/main/java/com/aroom/global/jwt/service/JwtService.java
  src/main/java/com/aroom/global/resolver/LoginInfo.java
  src/main/java/com/aroom/global/resolver/LoginInfoArgumentResolver.java
  src/main/java/com/aroom/global/security/account/AccountContext.java
  src/main/java/com/aroom/global/security/account/CustomUserDetailsService.java
  src/main/java/com/aroom/global/security/formlogin/CustomFormLoginFilter.java
  src/main/java/com/aroom/global/security/formlogin/CustomLoginToken.java
  src/main/java/com/aroom/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/aroom/global/security/jwt/JwtAuthenticationProvider.java
  src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
  src/test/java/com/aroom/global/jwt/JwtUtilsTest.java
Labels: enhancement

#72 feat/#71 room get v2
  src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestController.java
  src/main/java/com/aroom/domain/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/aroom/domain/accommodation/dto/response/RoomListInfoResponse.java
  src/main/java/com/aroom/domain/accommodation/service/AccommodationService.java
  src/test/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerTest.java
  src/test/java/com/aroom/domain/accommodation/service/AccommodationServiceTest.java
Labels: enhancement

#77 Feat/#75 fix reservation
  src/main/java/com/aroom/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
  src/main/java/com/aroom/domain/reservationRoom/repository/ReservationRoomRepository.java
  src/main/java/com/aroom/domain/room/dto/response/RoomImageResponse.java
  src/main/java/com/aroom/domain/room/dto/response/RoomReservationResponse.java
  src/main/java/com/aroom/domain/roomProduct/repository/RoomProductRepository.java
  src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
Labels: enhancement

#80 fix: 객실 이미지 Response 클래스 삭제에 따른 수정
  src/test/java/com/aroom/domain/reservation/controller/ReservationRestControllerTest.java
Labels: enhancement

#86 feat: spring rest docs 추가
  build.gradle
  src/test/java/com/aroom/docs/CommonDocsController.java
  src/test/java/com/aroom/docs/CommonDocsTest.java
  src/test/java/com/aroom/docs/RestDocsSupport.java
Labels: enhancement

#97 feat: AccessToken 재발급 API 문서화
  src/docs/asciidoc/jwt/jwt-api.adoc
  src/main/java/com/aroom/global/jwt/controller/JwtRefreshRestController.java
  src/test/java/com/aroom/global/jwt/docs/JwtRefreshRestControllerDocsTest.java
Labels: enhancement

#94 Feat/#93 member api documentation
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/members/members-api.adoc
  src/main/java/com/aroom/domain/member/controller/MemberController.java
  src/main/java/com/aroom/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/aroom/domain/member/service/MemberRegisterService.java
  src/test/java/com/aroom/domain/member/controller/MemberControllerTest.java
  src/test/java/com/aroom/domain/member/docs/RegisterControllerDocsTest.java
  src/test/java/com/aroom/domain/member/service/MemberRegisterServiceTest.java
  src/test/java/com/aroom/util/docs/CommonDocsController.java
  src/test/java/com/aroom/util/docs/CommonDocsTest.java
  src/test/java/com/aroom/util/docs/RestDocsHelper.java
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: enhancement

#102 feat: Security Authentication CustomizedMock 생성
  src/test/java/com/aroom/util/security/WithMockAccountContext.java
  src/test/java/com/aroom/util/security/WithMockAccountContextSecurityContextFactory.java
Labels: enhancement

#99 찜하기 기능 추가
  src/docs/asciidoc/favorites/favorites-api.adoc
  src/main/java/com/aroom/domain/favorite/controller/FavoriteController.java
  src/main/java/com/aroom/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/aroom/domain/favorite/service/FavoriteCreateRequest.java
  src/main/java/com/aroom/domain/favorite/service/FavoriteService.java
  src/main/java/com/aroom/domain/member/service/MemberQueryService.java
  src/test/java/com/aroom/domain/favorite/docs/FavoriteControllerDocsTest.java
  src/test/java/com/aroom/domain/favorite/service/FavoriteServiceTest.java
Labels: enhancement

#103 fix: 누락된 ControllerTestWithoutSecurityHelper 업데이트
  src/test/java/com/aroom/util/ControllerTestWithoutSecurityHelper.java
Labels: bug

#96 feat/#74 room cart post v2
  src/main/java/com/aroom/domain/cart/controller/CartRestControllerAdvice.java
  src/main/java/com/aroom/domain/cart/exception/CartNotFoundException.java
  src/main/java/com/aroom/domain/roomCart/controller/RoomCartRestController.java
  src/main/java/com/aroom/domain/roomCart/controller/RoomCartRestControllerAdvice.java
  src/main/java/com/aroom/domain/roomCart/dto/request/RoomCartRequest.java
  src/main/java/com/aroom/domain/roomCart/exception/RoomCartNotFoundException.java
  src/main/java/com/aroom/domain/roomCart/repository/RoomCartRepository.java
  src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
  src/main/java/com/aroom/domain/roomProduct/controller/RoomProductRestControllerAdvice.java
  src/main/java/com/aroom/domain/roomProduct/exception/RoomProductNotFoundException.java
  src/main/java/com/aroom/domain/roomProduct/repository/RoomProductRepository.java
Labels: enhancement

#105 test/#71 room get v2
  src/docs/asciidoc/accommodations/accommodations-api.adoc
  src/test/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerTest.java
  src/test/java/com/aroom/domain/accommodation/docs/AccommodationRestControllerDocsTest.java
  src/test/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryTest.java
  src/test/java/com/aroom/domain/accommodation/service/AccommodationServiceTest.java
Labels: enhancement

#109 feat: 재고, 판매량 업데이트, 동시성 제어 처리
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
  src/main/java/com/aroom/domain/room/model/Room.java
  src/main/java/com/aroom/domain/roomProduct/model/RoomProduct.java
  src/main/java/com/aroom/domain/roomProduct/repository/RoomProductRepository.java
Labels: enhancement

#108 fix: controller 테스트 코드 수정
  src/test/java/com/aroom/domain/reservation/controller/ReservationRestControllerTest.java
  src/test/java/com/aroom/domain/roomCart/controller/RoomCartRestControllerTest.java
Labels: bug

#112 Feat/#110 set restdocs
  src/docs/asciidoc/roomcarts/roomCarts-api.adoc
  src/main/java/com/aroom/domain/accommodation/dto/response/CartAccommodationResponse.java
  src/main/java/com/aroom/domain/room/dto/response/CartRoomResponse.java
  src/main/java/com/aroom/domain/roomCart/model/RoomCart.java
  src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
  src/main/java/com/aroom/domain/roomProduct/model/RoomProduct.java
  src/test/java/com/aroom/domain/roomCart/docs/RoomCartRestControllerDocsTest.java
  src/test/java/com/aroom/domain/roomCart/service/RoomCartServiceTest.java
Labels: enhancement

#117 Feat/#114 fix tset code reservation room cart
  src/docs/asciidoc/roomcarts/roomCarts-api.adoc
  src/main/java/com/aroom/domain/roomCart/model/RoomCart.java
  src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
  src/main/java/com/aroom/domain/roomProduct/model/RoomProduct.java
  src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
  src/test/java/com/aroom/domain/roomCart/controller/RoomCartRestControllerTest.java
Labels: bug

#122 fix: 장바구니가 없는 회원이 조회시 생기는 오류 수정
  src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
Labels: bug

#123 fix/startDate endDate 예외처리
  src/main/java/com/aroom/domain/accommodation/controller/AccommodationRestControllerAdvice.java
  src/main/java/com/aroom/domain/accommodation/service/AccommodationService.java
Labels: enhancement

#125 hotFix: 장바구니 객실 추가시, endDate 포함 x
  src/main/java/com/aroom/domain/roomCart/controller/RoomCartRestControllerAdvice.java
  src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
  src/main/java/com/aroom/domain/roomProduct/repository/RoomProductRepository.java
  src/test/java/com/aroom/domain/roomCart/service/RoomCartServiceTest.java
Labels: bug

#126 fix: 장바구니 추가 api 수정
  src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
  src/main/java/com/aroom/domain/roomProduct/repository/RoomProductRepository.java
Labels: bug

#127 fix: 찜하기 중복 방지 코드 추가
  src/main/java/com/aroom/domain/favorite/exception/AlreadyFavoriteException.java
  src/main/java/com/aroom/domain/favorite/exception/FavoriteNotFoundException.java
  src/main/java/com/aroom/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/aroom/domain/favorite/service/FavoriteService.java
  src/main/java/com/aroom/global/error/ErrorCode.java
Labels: bug

#129 Hotfix/add personnel room cart
  src/main/java/com/aroom/domain/room/dto/response/CartRoomResponse.java
  src/main/java/com/aroom/domain/roomCart/dto/request/RoomCartRequest.java
  src/main/java/com/aroom/domain/roomCart/model/RoomCart.java
  src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
  src/test/java/com/aroom/domain/roomCart/docs/RoomCartRestControllerDocsTest.java
  src/test/java/com/aroom/domain/roomCart/service/RoomCartServiceTest.java
  src/test/java/com/aroom/domain/roomProduct/repository/RoomProductRepositoryTest.java
Labels: bug, enhancement

#131 fix: reservation 테스트 코드 수정
  src/test/java/com/aroom/domain/reservation/controller/ReservationRestControllerTest.java
  src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
Labels: bug

#132 fix: roomCart test code fix
  src/test/java/com/aroom/domain/roomCart/controller/RoomCartRestControllerTest.java
  src/test/java/com/aroom/domain/roomCart/docs/RoomCartRestControllerDocsTest.java
  src/test/java/com/aroom/domain/roomCart/service/RoomCartServiceTest.java
  src/test/java/com/aroom/domain/roomProduct/repository/RoomProductRepositoryTest.java
Labels: enhancement

#133 fix: reservation 저장시 endDate 수정
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
Labels: bug

#134 docs: 누락된 주문 rest docs 추가
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/reservations/reservations-api.adoc
  src/test/java/com/aroom/domain/accommodation/docs/AccommodationControllerDocsTest.java
  src/test/java/com/aroom/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/aroom/util/fixture/AccommodationResponseFixture.java
  src/test/java/com/aroom/util/fixture/JwtFixture.java
  src/test/java/com/aroom/util/fixture/ReservationFixture.java
Labels: documentation

#136 fix: reservation restdocs 수정
  src/test/java/com/aroom/domain/reservation/docs/ReservationControllerDocsTest.java
  src/test/java/com/aroom/util/fixture/ReservationFixture.java
Labels: bug

#137 fix: reservation room image 수정
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
  src/main/java/com/aroom/domain/room/repository/RoomImageRepository.java
Labels: bug

#138 fix: 방 이미지 가져오기 수정
  src/main/java/com/aroom/domain/reservation/service/ReservationService.java
  src/test/java/com/aroom/domain/reservation/service/ReservationServiceTest.java
Labels: bug

#140 fix: 장바구니 조회 기능 오류 수정
  src/main/java/com/aroom/domain/roomCart/service/RoomCartService.java
Labels: bug

#141 Hotfix : 정렬조건 GroupBy절 삭제
  src/main/java/com/aroom/domain/accommodation/repository/AccommodationRepositoryImpl.java
Labels: bug
